version: '3.7' 

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: collectors
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      # porta host : porta container
      - 3306:3306
    volumes:
      # cartella sul host : cartella nel container
      - ./db:/var/lib/mysql